In [2]:
import numpy as np
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer

In [4]:
film = pd.read_csv('movies.csv')
film

movieId                                title  \
0            1                     Toy Story (1995)   
1            2                       Jumanji (1995)   
2            3              Grumpier Old Men (1995)   
3            4             Waiting to Exhale (1995)   
4            5   Father of the Bride Part II (1995)   
...        ...                                  ...   
10324   146684        Cosmic Scrat-tastrophe (2015)   
10325   146878           Le Grand Restaurant (1966)   
10326   148238       A Very Murray Christmas (2015)   
10327   148626                 The Big Short (2015)   
10328   149532  Marco Polo: One Hundred Eyes (2015)   

                                            genres  
0      Adventure|Animation|Children|Comedy|Fantasy  
1                       Adventure|Children|Fantasy  
2                                   Comedy|Romance  
3                             Comedy|Drama|Romance  
4                                           Comedy  
...                                            ...  
10324                    Animation|Children|Comedy  
10325                                       Comedy  
10326                                       Comedy  
10327                                        Drama  
10328                           (no genres listed)  

[10329 rows x 3 columns]

In [6]:
rating = pd.read_csv('ratings.csv')
rating

userId  movieId  rating   timestamp
0            1       16     4.0  1217897793
1            1       24     1.5  1217895807
2            1       32     4.0  1217896246
3            1       47     4.0  1217896556
4            1       50     4.0  1217896523
...        ...      ...     ...         ...
105334     668   142488     4.0  1451535844
105335     668   142507     3.5  1451535889
105336     668   143385     4.0  1446388585
105337     668   144976     2.5  1448656898
105338     668   148626     4.5  1451148148

[105339 rows x 4 columns]

In [7]:
film.isnull().sum()

movieId    0
title      0
genres     0
dtype: int64

In [10]:
filmc = film.copy()
for i in range(len(film)) :
    filmc['genres'][i]=film['genres'][i].replace("|"," ")

<ipython-input-10-d60ee21c7b9b>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filmc['genres'][i]=film['genres'][i].replace("|"," ")


In [12]:
cv = CountVectorizer()
x = cv.fit_transform(filmc['genres'])
print(cv.get_feature_names())
print(x.toarray())

['action', 'adventure', 'animation', 'children', 'comedy', 'crime', 'documentary', 'drama', 'fantasy', 'fi', 'film', 'genres', 'horror', 'imax', 'listed', 'musical', 'mystery', 'no', 'noir', 'romance', 'sci', 'thriller', 'war', 'western']
[[0 1 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [15]:
coscore = cosine_similarity(x.toarray())
coscore

array([[1.        , 0.77459667, 0.31622777, ..., 0.4472136 , 0.        ,
        0.        ],
       [0.77459667, 1.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.31622777, 0.        , 1.        , ..., 0.70710678, 0.        ,
        0.        ],
       ...,
       [0.4472136 , 0.        , 0.70710678, ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [14]:
joko = filmc[filmc['title'] == 'Superman vs. The Elite (2012)'].index.values[0]

In [19]:
jokofilm = sorted(list(enumerate(coscore[joko])), key=lambda x: x[1], reverse=True)
jokofilm[:5]

[(6260, 0.9999999999999998),
 (8637, 0.9999999999999998),
 (9370, 0.9999999999999998),
 (9570, 0.9999999999999998),
 (10167, 0.9999999999999998)]

In [24]:
j = 0
for i in jokofilm:
    if j < 5 and i[0] !=joko:
        print(str(filmc['title'].iloc[i[0]]))
        j += 1
    elif j >= 5 :
        break
    else :
        pass

Street Fighter II: The Animated Movie (Sutorîto Faitâ II gekijô-ban) (1994)
Batman: Under the Red Hood (2010)
Batman: The Dark Knight Returns, Part 2 (2013)
Justice League: Throne of Atlantis (2015)
Justice League: Gods and Monsters (2015)


In [25]:
rating

userId  movieId  rating   timestamp
0            1       16     4.0  1217897793
1            1       24     1.5  1217895807
2            1       32     4.0  1217896246
3            1       47     4.0  1217896556
4            1       50     4.0  1217896523
...        ...      ...     ...         ...
105334     668   142488     4.0  1451535844
105335     668   142507     3.5  1451535889
105336     668   143385     4.0  1446388585
105337     668   144976     2.5  1448656898
105338     668   148626     4.5  1451148148

[105339 rows x 4 columns]

In [26]:
ratmerge = rating.merge(film, left_on='movieId', right_on='movieId')
ratmerge

userId  movieId  rating   timestamp                        title  \
0            1       16     4.0  1217897793                Casino (1995)   
1            9       16     4.0   842686699                Casino (1995)   
2           12       16     1.5  1144396284                Casino (1995)   
3           24       16     4.0   963468757                Casino (1995)   
4           29       16     3.0   836820223                Casino (1995)   
...        ...      ...     ...         ...                          ...   
105334     668   140098     2.5  1450415424                Runoff (2015)   
105335     668   140816     2.5  1443288791             Tangerine (2015)   
105336     668   141472     2.5  1442679119  The 50 Year Argument (2014)   
105337     668   142488     4.0  1451535844             Spotlight (2015)   
105338     668   142507     3.5  1451535889        Pawn Sacrifice (2015)   

                    genres  
0              Crime|Drama  
1              Crime|Drama  
2              Crime|Drama  
3              Crime|Drama  
4              Crime|Drama  
...                    ...  
105334               Drama  
105335        Comedy|Drama  
105336  (no genres listed)  
105337            Thriller  
105338               Drama  

[105339 rows x 6 columns]

In [28]:
ratings = rating.pivot(index = 'userId', columns='movieId', values='rating')
ratings = ratings.replace([np.NaN,-1],0)
ratings.head()
ratingcor = ratings.corr()

In [29]:
widodo = ratmerge[ratmerge['title'] == 'Being Flynn (2012)']['movieId'].values[0]
widodo

95816

In [32]:
Widodoskor = pd.DataFrame()
skor = ratingcor.loc[widodo] * 5
skor = skor.sort_values(ascending=False)
skor

movieId
7086     5.000000
4801     5.000000
6898     5.000000
87660    5.000000
53038    5.000000
           ...   
1080    -0.079633
1073    -0.094189
231     -0.094907
367     -0.096955
344     -0.103537
Name: 95816, Length: 10325, dtype: float64

In [34]:
j = 0
for i in skor.index :
    if j < 5 and i != widodo:
        print((film[film['movieId']==i]['title'].values[0]))
        j += 1
    elif j >= 5 :
        break
    else :
        pass

Pygmalion (1938)
Little Foxes, The (1941)
Sweet Sixteen (2002)
Too Big to Fail (2011)
Red Dust (1932)
